name: CI pipeline
on:
  push:
    branches
-main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout code
        uses: actions/checkout@v4
      -name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      -name: Install dependencies
        run: |
          pytest
          -name: Build Docker image
        run: |
          docker build -t cicd-demo .
          